name: appointment-scheduler

volumes:
  local_postgres_data: {}

services:

  db:
    image: pgvector/pgvector:pg16
    container_name: pg_07
    env_file:
      - .env
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default


  db_ui:
    image: sosedoff/pgweb:0.13.1
    container_name: db_ui_07
    environment:
      - PGWEB_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    env_file:
      - .env
    depends_on: 
      db:
        condition: service_healthy
    ports: 
      - "5000:8081" 
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge